config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member #on: :memberでルーティングにidを含められる
    get :followers, on: :member
  end
  # resources :relationships
  resources :contacts
  resources :blogs do
    resources :comments, only:[:create, :destroy, :update, :edit]
  end
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  paginates_per 10
  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 140 }

  scope :index_all, -> {
    select(:id, :title, :content, :updated_at, :user_id) #フィールドごとにレコードを取得
    .order(updated_at: :asc) #created_atカラムの昇順に並び替え
    .includes(:user) #ユーザを事前に取得してN+1防止
  }
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # %i[ show edit update destroy ] = [:show, :edit, :update, :destroy]
  before_action :set_blog, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: :index

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.index_all.page(params[:page])
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @comment = Comment.new
    @comments = @blog.comments.page(params[:page]).per(7).reverse_order
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id #ブログを投稿した人 = 現在ログインしているユーザ
    respond_to do |format|
      if @blog.save
        NoticeMailer.sendmail_blog(@blog).deliver # 追記
        format.html { redirect_to blog_url(@blog), notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog.id), notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def button_text
    if action_name == "new"
      "create"
    elsif action_name == "edit"
      "edit"
    end
  end
end

app/views/blogs/_blog.html.erb
<div class="blog-panel">
   <p>by<%= blog.user.name %></p>
  <div class="d-flex align-items-baseline border-bottom border-dark">
    <h2 class="fw-bolder"><%= blog.title %></h2>
    <p class="ms-3"><%= blog.updated_at %></p>
  </div>
  <div class="blogs-content-box">
    <p class="blogs-content"><%= blog.content %></p>
  </div>
  <p class="text-primary"><%= "#{blog.comments.count} コメント" %></p>
  <% unless blog.user == current_user %>
    <% if @favorite.present? %>
      <%= button_to 'お気に入り解除する', favorite_path(@favorite), method: :delete, class: 'btn btn-danger', params:{blog_id: blog.id} %>
    <% else %>
      <%= button_to 'お気に入りする', favorites_path, class: 'btn btn-warning text-white', data: { turbo: false }, params:{blog_id: blog.id} %>
    <% end %>
  <% end %>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-item">
    <%= form.label :title, class:"form-label" %>
    <%= form.text_field :title,class:"form-control w-50" %>
  </div>

  <div class="form-item">
    <%= form.label :content, class:"form-label" %>
    <%= form.text_area :content, class:"form-control",rows:"3" %>
  </div>

  <div class="float-end">
      <%= form.submit button_text, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="body-y-margin container w-50">
  <h1 class="text-center">Editing blog</h1>
  <%= render "form", blog: @blog %>
  <div class="w-50 lh-lg">
    <p class="links-style d-inline"><%= link_to "Show this blog", @blog %> |</p>
    <p class="links-style d-inline"><%= link_to "Back to blogs", blogs_path %></p>
  </div>
</div>

app/views/blogs/index.html.erb
<div class="body-y-margin container w-75">
  <p class="notice"><%= notice %></p>
  <h1 class="fw-bold">Listing Blogs</h1>
  <div id="new-blog-link">
    <p class="links-style fw-bold"><%= link_to '新規ブログ作成', new_blog_path %></p>
  </div>
  <div class="row row-col">
    <% @blogs.each do |blog| %>
    <div class="d-flex flex-column col-xs-1 col-lg-6">
      <%= render blog %>
      <div class="show-btn d-flex justify-content-end">
        <%= link_to 'Show', blog, class: 'btn btn-primary' %>
      </div>
    </div>
    <% end %>
  </div>
  <div class="d-flex fs-5 justify-content-center mt-5"><%= paginate @blogs %></div>
</div>

app/views/blogs/new.html.erb
<div class="body-y-margin container w-50">
  <h1 class="text-center">New blog</h1>
  <%= render "form", blog: @blog %>
  <div class="w-50 lh-lg">
    <p class="links-style d-inline"><%= link_to "Back to blogs", blogs_path %></p>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="body-y-margin container w-50">
  <p class="notice"><%= notice %></p>
  <%= render @blog %>

  <%# コメント送る部分 %>

  <div class="comments ml-5 mt-5">
    <%= form_with(model: [@blog, @comment], local: true) do |f| %>
      <% if @comment.errors.any? %>
        <div style="color: red">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
        <ul>
          <% @comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
        </div>
      <% end %>

      <%= f.label :comment %>
      <%= f.text_area :comment, :size=>"60x3",placeholder: "コメントする" %>
      <%= f.hidden_field :blog_id, value: @blog.id %>
      <%= f.submit "投稿", class: "btn btn-success mb-4" %>
    <% end %>

    <p>コメント件数：<%= @comments.count %>/<%= @blog.comments.count%></p>
    <% @comments.each do |comment| %>
      <div class="comments-index mb-2">
        <%= comment.user.name %>
        <%= comment.created_at.strftime('%Y/%m/%d') %><br>
          <div class="d-flex">
            <%= comment.comment %>
              <% if comment.user == current_user %>
                <div class="comment-delete">
                  <%= button_to "delete", blog_comment_path(comment.blog, comment), method: :delete, class: 'btn btn-danger',form: { data: { turbo_confirm: "Are you sure?" } } %>
                </div>
                <%= link_to "edit", edit_blog_comment_path(comment.blog, comment), class: 'btn btn-primary' %>
            </div>
        </div>
              <% end %>
    <% end %>
    <%= paginate @comments %>
      </div>
  </div>

  <%# コメント送る部分 %>

  <div class="lh-lg">
    <p class="links-style d-inline"><%= link_to "Edit this blog", edit_blog_path(@blog) %> |</p>
    <p class="links-style d-inline"><%= link_to "Back to blogs", blogs_path %></p>
    <div class="float-end">
      <%= button_to "delete", @blog, method: :delete, class: 'btn btn-danger',form: { data: { turbo_confirm: "Are you sure?" } } %>
    </div>
  </div>

</div>