config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member #on: :memberでルーティングにidを含められる
    get :followers, on: :member
  end
  # resources :relationships
  resources :contacts
  resources :blogs do
    resources :comments, only:[:create, :destroy, :update, :edit]
  end
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs,  through: :favorites, source: :blog
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  paginates_per 2
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  has_one_attached :icon

  scope :index_all, -> {
    select(:id, :name, :email)
    .order(id: :asc)
    .includes(:blogs)
  }

  def is_followed_by?(user)
    passive_relationships.find_by(follower_id: user.id).present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]
  def index
    @users = User.index_all.page(params[:page])
  end

  def show; end

  def followings
    user = User.find(params[:id])
    @users = user.following
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user.html.erb
<div class="text-center ">
    <p class="mb-3 fw-bold fs-4"><%= user.name%></p>
     <div class="mb-2">
        <%= image_tag(user.icon, size: "150x150", class: "rounded-circle" ) if user.icon.attached? %>
     </div>
     <p class="text-small"><%= link_to user.following.count, followings_user_path(user)%>フォロー <%= link_to user.followers.count, followers_user_path(user)%>フォロワー</p>
    <p class="links-style d-inline"><%= link_to "Show", user_path(user) %></p>
    <% if user != current_user%>
        <% if user.is_followed_by?(current_user)%>
        <%= button_to "フォロー解除", user_relationships_path(user), method: :delete, class:"btn btn-danger", params:{user_id: user.id}%>
        <% else %>
        <%= button_to "フォロー", user_relationships_path(user), method: :post, class:"btn btn-primary", params:{user_id: user.id}%>
        <% end %>
    <% end %>
</div>

app/views/users/followers.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWERS</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                  <% if user.is_followed_by?(current_user) %>
                     <% if user.is_followed_by?(current_user) %>
                       <%= button_to "フォロー解除", user_relationships_path(user), method: :delete, class:"btn btn-danger"%>
                     <% else %>
                       <%= button_to "フォロー", user_relationships_path(user), method: :post, class:"btn btn-primary"%>
                     <% end %>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="container marketing">
  <div class="row d-flex justify-content-center">
    <div class="col-10 mt-5">
      <h1>FOLLOWING</h1>
      <table class="table text-center">
        <thead>
          <tr>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td>
                  <% if user.is_followed_by?(current_user) %>
                    <%= button_to "フォロー解除", user_relationships_path(user), method: :delete, class:"btn btn-danger"%>
                  <% else %>
                    <%= button_to "フォロー", user_relationships_path(user), method: :post, class:"btn btn-primary"%>
                  <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="body-y-margin container w-75">
  <h2 class="fw-bold text-center">All Users</h2>
  <div class="row row-col mt-5 mb-5">
    <% @users.each do |user| %>
      <div class="col-xs-1 col-md-6 mt-5 mb-5">
        <%= render user %>
      </div>
    <% end %>
    <div class="d-flex fs-5 justify-content-center"><%= paginate @users %></div>
    </div>
</div>

app/views/users/show.html.erb
<div class="body-y-margin container w-75">
  <h2 class="fw-bold text-center mb-5">User</h2>
  <div class="text-center">
    <p class="mb-3 fw-bold fs-4"><%= @user.name%></p>
     <div class="mb-2">
        <%= image_tag(@user.icon,width: "200px",height: "200px",  class: "rounded-circle") if @user.icon.attached? %>
     </div>
     <p class="mb-3 fw-bold"><%= @user.email%></p>
     <% if @user != current_user%>
       <% if @user.is_followed_by?(current_user)%>
         <%= button_to "フォロー解除", user_relationships_path(@user), method: :delete, class:"btn btn-danger"%>
       <% else %>
         <%= button_to "フォロー", user_relationships_path(@user), method: :post, class:"btn btn-primary"%>
       <% end %>
     <% end %>
     <% @user.blogs.each do |blog|%>
     <div class="text-start w-25 m-auto">
       <p><%= link_to blog.title, blog_path(blog.id) %></p>
     </div>
     <% end %>

    <p class="links-style d-inline"><%= link_to "back", :back %></p>
</div>
</div>