config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member #on: :memberでルーティングにidを含められる
    get :followers, on: :member
  end
  # resources :relationships
  resources :contacts
  resources :blogs do
    resources :comments, only:[:create, :destroy, :update, :edit]
  end
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :category, presence: true
  validates :content, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def confirm
    set_contact
    render :new if @contact.invalid?
  end

  def back
    set_contact
    render :new
  end

  def create
    set_contact
    if @contact.save
      ContactMailer.sendmail_user(@contact).deliver
      redirect_to blogs_url, notice: 'お問い合わせありがとうございます！'
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :category, :content)
  end

  def set_contact
    @contact = Contact.new(contact_params)
  end
end

app/views/contacts/_form.html.erb
<%= form_for(contact, url: confirm_path, data: { turbo: false }) do |form| %>

  <% if contact.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <%= pluralize(contact.errors.count, "error") %> prohibited this blog from being saved:
      </div>
      <div class="text-danger">
      <ul>
        <% contact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-item">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name,class:"form-control w-50" %>
  </div>

  <div  class="form-item">
    <%= form.label :email, class: "form-label" %>
    <%= form.text_field :email,class:"form-control w-50",placeholder:"example@email.com" %>
  </div>

  <div class="form-item">
    <%= form.label :category, class: "form-label" %>
    <div class="d-flex">
      <div class="m-3">
        <%= form.radio_button :category, :achieve, class:"form-check-input" %>
        <%= form.label :category, "Achieve", {value: :achieve,class:"form-option-label"} %>
      </div>
      <div class="m-3">
        <%= form.radio_button :category, :text, class:"form-check-input" %>
        <%= form.label :category, "テキスト", {value: :text,class:"form-option-label"} %>
      </div>
    </div>
    <div class="d-flex">
      <div class="m-3">
        <%= form.radio_button :category, :briefing, class:"form-check-input" %>
        <%= form.label :category, "説明会", {value: :briefing,class:"form-option-label"} %>
      </div>
      <div class="m-3">
        <%= form.radio_button :category, :other, class:"form-check-input" %>
        <%= form.label :category, "その他", {value: :other,class:"form-option-label"} %>
      </div>
    </div>
  </div>

  <div  class="form-item">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class:"form-control",rows:"3" %>
  </div>

  <div class="d-flex justify-content-end">
    <%= form.submit '入力内容確認', class:"btn btn-primary" %>
  </div>


<% end %>

app/views/contacts/confirm.html.erb
<div class="body-y-margin container w-50">
  <h1 class="fw-bold text-center">内容確認</h1>
  <div class="mt-5">

  <div class="form-item">
    <div class="d-flex">
      <p class="form-label me-2">name:</p>
      <p class="form-content d-block"><%= @contact.name %></p>
    </div>
  </div>

  <div class="form-item">
    <div class="d-flex">
      <p class="form-label me-2">email:</p>
      <p class="form-content d-block"><%= @contact.email %></p>
    </div>
  </div>


  <div class="form-item">
    <div class="d-flex">
      <p class="form-label me-2">category:</p>
      <p class="form-content d-block"><%= @contact.category %></p>
    </div>
  </div>

  <div class="form-item">
    <div class="d-flex">
      <p class="form-label me-2">content:</p>
      <p class="form-content d-block"><%= @contact.content %></p>
    </div>
  </div>

    <%= form_for(@contact) do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :category %>
      <%= f.hidden_field :content %>

      <div class="float-end"><%= f.submit '送信', class:"btn btn-primary" %></div>
    <% end %>
    <%= form_for @contact, url: back_path,data: { turbo: false } do |f| %>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :category %>
      <%= f.hidden_field :content %>
      <div><%= f.submit '入力画面に戻る', class:"btn btn-secondary" %></div>
    <% end %>
  </div>
</div>

app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

app/views/contacts/new.html.erb
<div class="body-y-margin container w-50">
  <h1 class="fw-bold text-center">お問い合わせ</h1>
  <%= render "form", contact: @contact %>
</div>