config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member #on: :memberでルーティングにidを含められる
    get :followers, on: :member
  end
  # resources :relationships
  resources :contacts
  resources :blogs do
    resources :comments, only:[:create, :destroy, :update, :edit]
  end
  resources :favorites, only: [:create, :destroy, :index]
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_footer.html.erb
<footer class="footer text-white text-center">
  <p>&copy touma_fukushi.Inc</p>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
<nav class="d-flex justify-content-between bg-dark  align-items-center">
  <div class="d-flex">
    <p><%= link_to "Home", root_path,class:"item"%></p>
    <p><%= link_to "blogs", blogs_path,class:"item" %></p>
    <p><%= link_to "contact", new_contact_path,class:"item" %></p>
  </div>
  <div class="d-flex  align-items-center">
     <% if user_signed_in? %>
      <p><%= link_to "Users", users_path,class:"item" %></p>
      <p><%= link_to "Mypage", user_path(current_user),class:"item" %></p>
      <p><%= link_to "favarites", favorites_path,class:"item" %></p>
      <p><%= link_to "logout", destroy_user_session_path, method: :delete,class:"item" %></p>
      <p><%= link_to "edit-prof", edit_user_registration_path, method: :delete,class:"item" %></p>
     <% else %>
      <p><%= link_to "login", new_user_session_path, class:"item" %></p>
     <% end %>
  </div>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Achieve2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <% if user_signed_in? %>
      <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
      <p><%= link_to "プロフィール編集", edit_user_registration_path, method: :delete %></p>
    <% end %>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/header" %>
      <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>